export const cartActionTypes = {
  SET_CART_HIDDEN: "SET_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REDUCE_ITEM_QUANTITY: "REDUCE_ITEM_QUANTITY",
  ADJUST_QUANTITY: "ADJUST_QUANTITY",
};
